# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir z:/git/github/DAT096-NN1/mig_7series_0_ex/mig_7series_0_ex.cache/wt [current_project]
set_property parent.project_path z:/git/github/DAT096-NN1/mig_7series_0_ex/mig_7series_0_ex.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.4 [current_project]
set_property ip_output_repo z:/git/github/DAT096-NN1/mig_7series_0_ex/mig_7series_0_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_afifo.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_cmd_gen.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_cmd_prbs_gen.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_data_prbs_gen.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_init_mem_pattern_ctr.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_memc_flow_vcontrol.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_memc_traffic_gen.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_rd_data_gen.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_read_data_path.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_read_posted_fifo.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_s7ven_data_gen.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_tg_prbs_gen.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_tg_status.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_traffic_gen_top.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_vio_init_pattern_bram.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_wr_data_gen.v
  z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/mig_7series_v4_2_write_data_path.v
}
read_vhdl -library xil_defaultlib z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/example_top.vhd
read_ip -quiet z:/git/github/DAT096-NN1/mig_7series_0_ex/mig_7series_0_ex.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all z:/git/github/DAT096-NN1/mig_7series_0_ex/mig_7series_0_ex.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all z:/git/github/DAT096-NN1/mig_7series_0_ex/mig_7series_0_ex.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/example_top.xdc
set_property used_in_implementation false [get_files z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/example_top.xdc]
set_property processing_order EARLY [get_files z:/git/github/DAT096-NN1/mig_7series_0_ex/imports/example_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top example_top -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef example_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file example_top_utilization_synth.rpt -pb example_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
