##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Wed Feb 17 11:23:42 2021

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A200T-FBG676
##                    Speedgrade:        -2
##                    Design Entry:      VHDL
##                    Frequency:         400 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->SODIMMs->MT8JTF12864HZ-1G6
## Data Width: 64
## Time Period: 2500
## Data Mask: 0
##################################################################################################
############## NET - IOSTANDARD ##################


# PadFunction: IO_L1N_T0_16 
set_property IOSTANDARD LVCMOS25 [get_ports {init_calib_complete}]
set_property PACKAGE_PIN H15 [get_ports {init_calib_complete}]

# PadFunction: IO_L6P_T0_16 
set_property IOSTANDARD LVCMOS25 [get_ports {tg_compare_error}]
set_property PACKAGE_PIN H16 [get_ports {tg_compare_error}]

