# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Z:/git/github/DAT096-NN1/constraints/Nexys4DDR_Master.xdc

# IP: ip/mig_7series_DDR/mig_7series_DDR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_DDR || ORIG_REF_NAME==mig_7series_DDR} -quiet] -quiet

# XDC: ip/mig_7series_DDR/mig_7series_DDR/user_design/constraints/mig_7series_DDR.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_DDR || ORIG_REF_NAME==mig_7series_DDR} -quiet] -quiet

# XDC: ip/mig_7series_DDR/mig_7series_DDR/user_design/constraints/mig_7series_DDR_ooc.xdc
